defaults:
  - # All posts are authored by me
      scope:
        path: ""
        type: "posts"
      values:
        layout: "default"
        author: "Alex Ati"
  - # All pages are authored by me
      scope:
        path: ""
        type: "pages"
      values:
        layout: "default"
        author: "Alex Ati"
  - # Drafts are not published
      scope:
        path: "_drafts"
        type: "posts"
      values:
        published: false
