defaults:
  - # All pages are authored by me
      scope:
        path: ""
      values:
        layout: "default"
        author: "Alex Ati"
  - # Drafts are not published
      scope:
        path: "_drafts"
      values:
        published: false
